write_finra_stock_report:
  description: >
      Write a FINRA approved stock report about {company_ticker}.
  expected_output: >
    A FINRA approved stock report about {company_ticker}.
  agent: finra_stock_report_writer
